import React from "react";
import useCollapse from "react-collapsed";
import "../expandlist/Expand.css";

function Section(props) {
  const config = {
    defaultExpanded: props.defaultExpanded || false,
    collapsedHeight: props.collapsedHeight || 0,
  };
  const { getCollapseProps, getToggleProps, isExpanded } = useCollapse(config);
  return (
    <div className="collapsible">
      <div className="header" {...getToggleProps()}>
        <div className="title">{props.title}</div>
        <div className="icon">
          <i
            className={"fas fa-chevron-circle-" + (isExpanded ? "up" : "down")}
          ></i>
        </div>
      </div>
      <div {...getCollapseProps()}>
        <div className="content">{props.children}</div>
      </div>
    </div>
  );
}
function Collapsible() {
    var myJson = {
      http_code: 200,
      message: "Category list fetched successfully",
      data: {
        total_records: 5,
        categories: [
          {
            id: 50,
            name: "Style",
            slug: "style",
            image: null,
            icon: null,
            description: null,
            parent_id: 0,
            level: 1,
            position: 0,
            created_at: "2022-11-02T08:23:42.000000Z",
            updated_at: "2022-11-02T08:23:42.000000Z",
            home_status: 0,
            priority: 1,
            is_display: "0",
            status: "1",
            meta_keywords: "Fashion Style",
            meta_description: null,
            type: "category",
            children_categories: [
              {
                id: 53,
                name: "Modern",
                parent_id: 50,
                slug: "modern",
                level: 2,
                status: "1",
                priority: 1,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 54,
                name: "Standard",
                parent_id: 50,
                slug: "standard",
                level: 2,
                status: "1",
                priority: 2,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 55,
                name: "Minimal",
                parent_id: 50,
                slug: "minimal",
                level: 2,
                status: "1",
                priority: 3,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 56,
                name: "Vintage",
                parent_id: 50,
                slug: "vintage",
                level: 2,
                status: "1",
                priority: 4,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 57,
                name: "Elegant",
                parent_id: 50,
                slug: "elegant",
                level: 2,
                status: "1",
                priority: 5,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 58,
                name: "Ancient",
                parent_id: 50,
                slug: "ancient",
                level: 2,
                status: "1",
                priority: 6,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
            ],
            translations: [],
          },
          {
            id: 51,
            name: "Men Wear",
            slug: "men-wear",
            image: null,
            icon: null,
            description: null,
            parent_id: 0,
            level: 1,
            position: 0,
            created_at: "2022-11-02T09:27:00.000000Z",
            updated_at: "2022-11-02T09:27:00.000000Z",
            home_status: 0,
            priority: 2,
            is_display: "0",
            status: "1",
            meta_keywords: "Men Wear",
            meta_description: "Men Wear",
            type: "category",
            children_categories: [
              {
                id: 59,
                name: "Top Wear",
                parent_id: 51,
                slug: "top-wear",
                level: 2,
                status: "1",
                priority: 1,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [
                  {
                    id: 60,
                    name: "T-Shirt",
                    parent_id: 59,
                    slug: "t-shirt",
                    level: 3,
                    status: "1",
                    priority: 1,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                  {
                    id: 61,
                    name: "Casual Shirt",
                    parent_id: 59,
                    slug: "casual-shirt",
                    level: 3,
                    status: "1",
                    priority: 2,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                  {
                    id: 62,
                    name: "Formal Shirt",
                    parent_id: 59,
                    slug: "formal-shirt",
                    level: 3,
                    status: "1",
                    priority: 3,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                  {
                    id: 63,
                    name: "Blazers & Coats",
                    parent_id: 59,
                    slug: "blazers-coats",
                    level: 3,
                    status: "1",
                    priority: 4,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                  {
                    id: 64,
                    name: "Suits",
                    parent_id: 59,
                    slug: "suits",
                    level: 3,
                    status: "1",
                    priority: 5,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                  {
                    id: 65,
                    name: "Jackets",
                    parent_id: 59,
                    slug: "jackets",
                    level: 3,
                    status: "1",
                    priority: 6,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                  {
                    id: 68,
                    name: "Belt, Scarves and More",
                    parent_id: 59,
                    slug: "belt-scarves-and-more",
                    level: 3,
                    status: "1",
                    priority: 7,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                  {
                    id: 69,
                    name: "Watches & Wearables",
                    parent_id: 59,
                    slug: "watches-wearables",
                    level: 3,
                    status: "1",
                    priority: 8,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                ],
                translations: [],
              },
              {
                id: 71,
                name: "Bottomwear",
                parent_id: 51,
                slug: "bottomwear",
                level: 2,
                status: "1",
                priority: 2,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [
                  {
                    id: 72,
                    name: "Jeans",
                    parent_id: 71,
                    slug: "jeans",
                    level: 3,
                    status: "1",
                    priority: 0,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                  {
                    id: 73,
                    name: "Casual Trousers",
                    parent_id: 71,
                    slug: "casual-trousers",
                    level: 3,
                    status: "1",
                    priority: 2,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                  {
                    id: 74,
                    name: "Formal Trousers",
                    parent_id: 71,
                    slug: "formal-trousers",
                    level: 3,
                    status: "1",
                    priority: 3,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                  {
                    id: 75,
                    name: "Shorts",
                    parent_id: 71,
                    slug: "shorts",
                    level: 3,
                    status: "1",
                    priority: 4,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                ],
                translations: [],
              },
              {
                id: 67,
                name: "Watches & Wearables",
                parent_id: 51,
                slug: "watches-wearables",
                level: 2,
                status: "0",
                priority: 3,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 66,
                name: "Footwear",
                parent_id: 51,
                slug: "footwear",
                level: 2,
                status: "1",
                priority: 4,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 70,
                name: "Gadgets",
                parent_id: 51,
                slug: "gadgets",
                level: 2,
                status: "1",
                priority: 5,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
            ],
            translations: [],
          },
          {
            id: 52,
            name: "Women Wear",
            slug: "women-wear",
            image: null,
            icon: null,
            description: null,
            parent_id: 0,
            level: 1,
            position: 0,
            created_at: "2022-11-02T09:28:10.000000Z",
            updated_at: "2022-11-02T09:28:10.000000Z",
            home_status: 0,
            priority: 3,
            is_display: "0",
            status: "1",
            meta_keywords: "Women WearWomen Wear",
            meta_description: null,
            type: "category",
            children_categories: [
              {
                id: 76,
                name: "Top Wear",
                parent_id: 52,
                slug: "top-wear",
                level: 2,
                status: "1",
                priority: 1,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 77,
                name: "Bottom Wear",
                parent_id: 52,
                slug: "bottom-wear",
                level: 2,
                status: "1",
                priority: 2,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 79,
                name: "Jewellery",
                parent_id: 52,
                slug: "jewellery",
                level: 2,
                status: "1",
                priority: 3,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 78,
                name: "Gadgets",
                parent_id: 52,
                slug: "gadgets",
                level: 2,
                status: "1",
                priority: 4,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
            ],
            translations: [],
          },
          {
            id: 2,
            name: "Kids",
            slug: "kids",
            image:
              "https://brandx-s3-assets.s3.amazonaws.com/images/category/1666248252download (1).png",
            icon: null,
            description: null,
            parent_id: 0,
            level: 1,
            position: 0,
            created_at: "2022-05-30T12:29:01.000000Z",
            updated_at: "2022-11-02T10:44:49.000000Z",
            home_status: 1,
            priority: 4,
            is_display: "0",
            status: "1",
            meta_keywords: "Test Meta data",
            meta_description: "Meta Description",
            type: "category",
            children_categories: [
              {
                id: 4,
                name: "Boys Clothings",
                parent_id: 2,
                slug: "boys-clothings",
                level: 2,
                status: "1",
                priority: 1,
                icon: null,
                is_display: "0",
                meta_keywords: "Test Meta data",
                meta_description: "meta description",
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 42,
                name: "Girls Clothing",
                parent_id: 2,
                slug: "girls-clothing",
                level: 2,
                status: "1",
                priority: 2,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 3,
                name: "Toys",
                parent_id: 2,
                slug: "toys",
                level: 2,
                status: "1",
                priority: 3,
                icon: null,
                is_display: "0",
                meta_keywords: "test keywordss",
                meta_description: "test description",
                type: "category",
                children_categories: [
                  {
                    id: 12,
                    name: "Soft Toys",
                    parent_id: 3,
                    slug: "soft-toys",
                    level: 2,
                    status: "1",
                    priority: 0,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                  {
                    id: 82,
                    name: "Activity Toys",
                    parent_id: 3,
                    slug: "activity-toys",
                    level: 3,
                    status: "1",
                    priority: 0,
                    icon: null,
                    is_display: "0",
                    meta_keywords: null,
                    meta_description: null,
                    type: "category",
                    children_categories: [],
                    translations: [],
                  },
                ],
                translations: [],
              },
            ],
            translations: [],
          },
          {
            id: 7,
            name: "Beauty Products",
            slug: "beauty-products",
            image:
              "https://brandx-s3-assets.s3.ap-south-1.amazonaws.com/images/category/1665580489567605_2.png",
            icon: null,
            description: null,
            parent_id: 0,
            level: 1,
            position: 0,
            created_at: "2022-05-30T14:33:49.000000Z",
            updated_at: "2022-05-30T14:33:49.000000Z",
            home_status: 0,
            priority: 4,
            is_display: "0",
            status: "1",
            meta_keywords: null,
            meta_description: null,
            type: "category",
            children_categories: [
              {
                id: 81,
                name: "MakeUp",
                parent_id: 7,
                slug: "makeup",
                level: 2,
                status: "1",
                priority: 0,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 80,
                name: "SkinCare",
                parent_id: 7,
                slug: "skincare",
                level: 2,
                status: "1",
                priority: 1,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
              {
                id: 10,
                name: "Lipstick",
                parent_id: 7,
                slug: "lipstick",
                level: 2,
                status: "0",
                priority: 5,
                icon: null,
                is_display: "0",
                meta_keywords: null,
                meta_description: null,
                type: "category",
                children_categories: [],
                translations: [],
              },
            ],
            translations: [],
          },
        ],
      },
    };
  var list = [
    {
      title: "General",
      subcategory: [
        { subTitle: "Syed" },
        { subTitle: "Aabid" },
        { subTitle: "Ahamed" },
      ],
    },
    {
      title: "Manager",
      subcategory: [
        { subTitle: "Mohammed" },
        { subTitle: "Sheeraz" },
      ],
    },
    {
      title: "Police",
      subcategory: [
        { subTitle: "Shariq" },
        { subTitle: "Nawaz" },
      ],
    },
  ];
  return (
    <div className="preferences">
      {myJson.data.categories.map((item, index) => {
        return (
          <Section title={item.name} defaultExpanded="true">
           {
            item.children_categories.map((subItem, sunIndex) => {
                return <ul>{subItem.name}</ul>;
            })
           }
           
          </Section>
        );
      })}
    </div>
  );
}
export default Collapsible;
// function App() {
//   return <Collapsible />;
// }
//  App;
